### ISSUE TITLE
Dependency on non-standard INFO 'LEN' field for annotating complex indels

### ISSUE THREAD

**Issue by jwhsanger** [cancerit/VAGrENT#10]
AnnotateVcf.pl

::parse_vcf_record  - line 324:

    my $max = $min + ($vcf->get_info_field($record->[$INFO_COL], 'LEN') - 1);

This restricts Vagrent to running on cgpPindel generated files only. For example 1000g variant files do not contain this INFO key.

**Comment by AndyMenzies** [comment]
Agreed, thats iffy.

The reference change length is already defined in that function

my $ref_len = length $ref;

This is only used for deletions or complex changes, so I propose we change the line to

my $max = $min + ($ref_len - 2);

We need to deduct 2, one for the extra VCF anchor base in the reference sequence and one for the inclusive start position.

Sound good?

**Comment by AndyMenzies** [comment]
Fixed in release 2.1.2
