### ISSUE TITLE
Allow local paths to ensembl GTF and fasta files in cache creation scripts 

### ISSUE THREAD

**Issue by AndyMenzies** [cancerit/VAGrENT#13]
We need to allow for locally downloaded versions of the Ensembl reference files to be used instead of downloading directly from the Ensembl FTP site.

This was highlighted when we realised that most Human GRCh38 tend to include 'chr' at the beginning of their chromosome identifiers, however the ensembl GTF files don't.

**Comment by jsmedmar** [comment]
I think this relates to #27

**Comment by AndyMenzies** [comment]
Resolved by release V3.3.0
