### ISSUE TITLE
Unable to run Admin_GeneRegionBedDumper.pl

### ISSUE THREAD

**Issue by sb43** [cancerit/VAGrENT#18]
cgppipe@cgp-1-2-01:~/canpipe/live/ref/human/GRCh38_full_analysis_set_plus_decoy_hla/vagrent/77$ /software/CGP/canpipe/live/bin/canpipe_live /software/CGP/canpipe/live/bin/Admin_GeneRegionBedDumper.pl -sp human -as 77 -fai ../../genome.fa.fai -c vagrent.cache.gz
EVAL_ERROR: You must specify a region in the format chr, chr:start or chr:start-end at /software/CGP/canpipe/live/lib/perl5/x86_64-linux-thread-multi/Bio/DB/HTS/Tabix.pm line 64.

OS_ERROR: No such file or directory
A problem occurred at /software/CGP/canpipe/live/bin/Admin_GeneRegionBedDumper.pl line 145.

**Comment by keiranmraine** [comment]
`-as` should be the genome assembly not the Ensembl build

**Comment by keiranmraine** [comment]
The problem is that the `fai` file has 'chr' prefix and the vagrent cache doesn't.  This is invalid

**Comment by sb43** [comment]
Solution @keiranmraine is correct, the workaround is to update vagrent cache file and add chr prefix to chromosome names and get rid of all non standard chromosomes.
