### ISSUE TITLE
v3.2.3 Fails to compile

### ISSUE THREAD

**Issue by drjsanger** [cancerit/VAGrENT#26]
```
t/2_pl_compile.t ... 5/? 
#   Failed test 'Compilation check: /blah/projects/git/VAGrENT/t/../bin/AnnotateVcf.pl'
#   at t/2_pl_compile.t line 58.
# Looks like you failed 1 test of 5.
t/2_pl_compile.t ... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
t/3_stable_sort.t .. 1/? 
#   Failed test 'Constructed base comparison VCF'
#   at t/3_stable_sort.t line 46.
#          got: '512'
#     expected: '0'

#   Failed test 'Constructed comparison VCF No. 1'
#   at t/3_stable_sort.t line 56.
#          got: '512'
#     expected: '0'
```

**Comment by keiranmraine** [comment]
@drjsanger what OS, perl version?

**Comment by keiranmraine** [comment]
Worked fine on [travis](https://travis-ci.org/cancerit/VAGrENT/builds/287025784?utm_source=github_status&utm_medium=notification) with [perl5.22](https://github.com/cancerit/VAGrENT/blob/7f34dd03494597661739d786c1e9fb3c9c5114b2/.travis.yml#L24)

**Comment by drjsanger** [comment]
That could be it. Machine had perl-5.16.3

**Comment by keiranmraine** [comment]
The test shows that `AnnotateVcf.pl` failed to compile, which is also why `3_stable_sort.t` failed (as it executes it).

There were no changes in `AnnotateVcf.pl` between versions and the only changes were the addition of the new test, it's data files, version bump and a few sort entries:

https://github.com/cancerit/VAGrENT/compare/v3.2.2...v3.2.3?w=1

@drjsanger could you retry an install with that version in the same environment?

**Comment by drjsanger** [comment]
I succeeded with 3.2.1. 

https://github.com/cancerit/VAGrENT/compare/v3.2.1...v3.2.2?w=1

`File::Copy` was added to `AnnotateVcf.pl`. But that's a core and doesn't cause any issues:

```
$ perl -MFile::Copy -e 'use File::Copy;'
$ which perl
/blah/perl-5.16.3/bin/perl
```

1. Lone install of `v3.2.2` using perl-5.16.3 has succeeded. 
2. Lone install of `v3.2.3` using perl-5.16.3 has succeeded.

Can only assume some weirdness to do with a previous install or `/tmp/` clearing up or filling up mid install.

```
t/1_pm_compile.t ... ok    
t/2_pl_compile.t ... 4/? 
#   Failed test 'Compilation check: /nfs/users/nfs_d/drj/projects/git/VAGrENT/t/../bin/AnnotateVcf.pl'
#   at t/2_pl_compile.t line 58.
# Looks like you failed 1 test of 5.
t/2_pl_compile.t ... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
t/3_stable_sort.t .. 1/? 
#   Failed test 'Constructed base comparison VCF'
#   at t/3_stable_sort.t line 46.
#          got: '512'
#     expected: '0'

#   Failed test 'Constructed comparison VCF No. 1'
#   at t/3_stable_sort.t line 56.
#          got: '512'
#     expected: '0'
diff: /tmp/ARilHDxEia/a.vcf: No such file or directory
diff: /tmp/ARilHDxEia/b.vcf: No such file or directory
Bailout called.  Further testing stopped:  Diff found errors see: /tmp/ARilHDxEia, you will need to cleanup.
FAILED--Further testing stopped: Diff found errors see: /tmp/ARilHDxEia, you will need to cleanup. 
```

**Comment by keiranmraine** [comment]
So a no op
