### ISSUE TITLE
Build Cache for Ensembl 91 and GRCh37

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/VAGrENT#27]
I was wondering if its possible to build a Vagrent Cache for Ensemble 91 and GRCh37.    

The problem is that there is not a cdna release for `GRCh37`.

```bash
Admin_EnsemblReferenceFileGenerator.pl \
        -species human \
        -assembly GRCh37 \
        -database homo_sapiens_core_91_37 \
        -ccds CCDS2Sequence.current.txt \
        -ftp ftp://ftp.ensembl.org/pub/release-91/fasta/homo_sapiens/cdna/ \
        -outputDir .
```

I'm not an Ensembl/Bioinformatics expert so don't be surprised if this question doesn't make sense.

**Comment by jsmedmar** [comment]
I found this one `ftp://ftp.ensembl.org/pub/grch37/release-91/fasta/homo_sapiens/cdna/`, but had to temporarily update this [line][line] in `Admin_EnsemblReferenceFileGenerator.pl` to: 

```perl
const my $ENSEMBL_VERSION_PATTERN => qr/^ftp\:\/\/ftp\.ensembl\.org\/pub\/grch37\/release\-(\d+?)\//;
```

Currently testing.

[line]: https://github.com/cancerit/VAGrENT/blob/dev/bin/Admin_EnsemblReferenceFileGenerator.pl#L56

**Comment by jsmedmar** [comment]
I think this is not going to work because there is not a database in the core release:

```
ftp://ftp.ensembl.org/pub/release-91/mysql/
```

However there is one available here

```
ftp://ftp.ensembl.org/pub/grch37/release-91/mysql/homo_sapiens_core_91_37/
```

I couldn't find where in the code the connection to the ensembl db is done.

**Comment by AndyMenzies** [comment]
The Ensembl release method for the latest GRCh37 is very non standard and doesn't fit with the usual structure of their FTP site.  They are handling it as a special case, as a result we can't support it directly.  

However, I am in the middle of a complete rewrite of the reference generation code.  This will allow you to specify local paths to the Ensembl data, as well as cope with some of the updates Ensembl has made to their FTP exported data in recent releases.

**Comment by jsmedmar** [comment]
Hey @AndyMenzies thanks so much for replying. Looking forward to these changes.

**Comment by jsmedmar** [comment]
@AndyMenzies does #28 is related to this issue?

**Comment by AndyMenzies** [comment]
Yes, that will be the next release.  However I've been side tracked with other issues and haven't had a chance to finalise testing or role the release.

**Comment by AndyMenzies** [comment]
I've just rolled out the new v3.3.0 release, this will let you specify your own locally dowloaded fasta and GFF/GTF files to build from and should allow you to get round the GRCh37 freeze issue on the Ensembl FTP site.

**Comment by jsmedmar** [comment]
I want to leave this in case anyone land here in the future.
At the moment of writing there was no `91` version for the `--features ` file `Homo_sapiens.GRCh37.87.gff3.gz`.

### Cache for Ensemble 91 and GRCh37

1. First download reference data:

        wget ftp://ftp.ensembl.org/pub/grch37/release-91/fasta/homo_sapiens/ncrna/Homo_sapiens.GRCh37.ncrna.fa.gz
        wget ftp://ftp.ensembl.org/pub/grch37/release-91/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.gff3.gz
        wget ftp://ftp.ensembl.org/pub/grch37/release-91/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.cdna.all.fa.gz
        wget ftp://ftp.ncbi.nlm.nih.gov/pub/CCDS/current_human/CCDS2Sequence.current.txt
        wget ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5.tar.gz
        tar -C . --strip-components 1 -zxf core_ref_GRCh37d5.tar.gz
        rm core_ref_GRCh37d5.tar.gz

1. Current directory state:

        $ ls ./
            CCDS2Sequence.current.txt
            Homo_sapiens.GRCh37.87.gff3.gz
            Homo_sapiens.GRCh37.cdna.all.fa.gz
            Homo_sapiens.GRCh37.ncrna.fa.gz
            genome.fa
            genome.fa.dict
            genome.fa.fai

1. Run using docker:

        docker run -v `pwd`:/test -w /test -it --entrypoint '' \
            leukgen/docker-vagrent Admin_EnsemblReferenceFileGenerator.pl \
                --species human \
                --assembly GRCh37 \
                --database homo_sapiens_91_37 \
                --ccds ./CCDS2Sequence.current.txt \
                --cdna_fa ./Homo_sapiens.GRCh37.cdna.all.fa.gz \
                --ncrna_fa ./Homo_sapiens.GRCh37.ncrna.fa.gz \
                --fai ./genome.fa.fai \
                --feature ./Homo_sapiens.GRCh37.87.gff3.gz \
                --output .

**Comment by AndyMenzies** [comment]
This is why the Ensembl GRCh37 freeze is difficult to handle.  The GRCh37 Ensembl 91 release doesn't actually have any new data of its own, it symbolically links back to parts of older releases.  The transcript fasta files were last updated in Ensembl 83 while the GTF/GFF3 files are actually from Ensembl 87.

The only way this can be supported is by downloading comparable files manually and processing them like this.  I would consider this an advanced use case only to be conducted by some one who really knows what they are doing.  Its very easy to get this wrong if you try to combine incompatible files.
