### ISSUE TITLE
SO numbers inserted into VC field

### ISSUE THREAD

**Issue by JocelynSP** [cancerit/VAGrENT#31]
Running Vagrent on Pindel outputs. Some VC fields, as well as the variant class such as 'stop_loss' or 'complex_change_in_transcript', have the Sequence Ontology number in the VC field as well.
In an example file, there are 120 records that include 
VC=complex_change_in_transcript
, usually with other class labels as well, and 13 records that include instead VC=SO:0001577:complex_change_in_transcript
Which is inconsistent, unnecessary as the SO number is already in 2 other fields, and complicates searches on VC

**Comment by AndyMenzies** [comment]
Yes it will do that. The VC field is populated from a look up file, [SequenceOntologySummary.ini](https://github.com/cancerit/VAGrENT/blob/master/share/SequenceOntologySummary.ini), this file contains a list of term combinations and a equivalent abbreviation.  We originally populated it with classifications we observed having processed several million variants. When there is no abbreviation in the file it falls back to using the full classification instead.

If you are seeing the full SO class in the VC field, you must have found a new combination we've never seen before.  

To get these classes abbreviated we need to add them to the look up file.  Either you can do that yourself in your local installed copy, or you can supply me with the full VCF records for these variants I can add them to the main project here.

**Comment by JocelynSP** [comment]
Thanks for the helpful reply. I had failed to filter the Pindel output, so I was getting a lot of very low-quality calls. When I restricted to calls that passed the filters the new combinations no longer appeared
