### ISSUE TITLE
Admin_EnsemblReferenceFileGenerator.pl not producing any result for a list of transcripts

### ISSUE THREAD

**Issue by nvolkovaGEL** [cancerit/VAGrENT#41]
Hello,
I am trying to generate a vagrent.cache file for a pre-specified list of Ensembl transcripts. The list looks as a list of IDs:
> ENST00000389048
> ENST00000343823
> ENST00000447712
> ENST00000409261
> ...

Then I try running this script:
`perl VAGrENT/bin/Admin_EnsemblReferenceFileGenerator.pl --species human --assembly GRCh38 --database homo_sapiens_core_99_38 --ccds CCDS2Sequence.current.txt --features Homo_sapiens.GRCh38.99.gtf --cdna_fa Homo_sapiens.GRCh38.cdna.all.fa --ncrna_fa Homo_sapiens.GRCh38.ncrna.fa -output vagrent_cache/ --trans_list List_of_transcripts.tsv --fai GRCh38.fa.fai`
But it produces empty files, despite the fact that the transcripts in the list are grep-able in the CDNA and GTF files. Am I doing something wrong? The GTF, DNA and NCRNA come from Ensembl v.99.

**Comment by AndyMenzies** [comment]
Hi

Using the dynamic download reference generation works for Ensembl 99 Human

Admin_EnsemblReferenceFileGenerator.pl -sp Human -as GRCh38 -d homo_sapiens_core_99_38 -f ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/cdna/ -o /noddy/output/location

If I add a transcript list with the your 4 transcripts from below, this also works and generates a cache file with the specified transcripts.

Admin_EnsemblReferenceFileGenerator.pl -sp Human -as GRCh38 -d homo_sapiens_core_99_38 -f ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/cdna/ -tl trans.list -o /noddy/output/location

Running it this way will use the gff3 annotation file on Ensembl’s ftp site in preference to the gtf file, and that might be the difference.  Could you download the gff3 file and try it with that instead of the gtf file?

Andy

**Comment by nvolkovaGEL** [comment]
Hi Andy,
Unfortunately, using Homo_sapiens.GRCh38.99.gff3 did not help, it still reports that everything worked fine:
> Downloading Files -------- Skipped, files locally supplied
> Obtaining Filtered Transcript List ----- Skipped, files locally supplied
> Building Cache Files ----- Done

But returns a set of empty files:
> -rwxrwxrwx 28 Jun 12 14:55 vagrent.human.GRCh38.homo_sapiens_core_99_38.cache.gz
> -rwxrwxrwx 75 Jun 12 14:55 vagrent.human.GRCh38.homo_sapiens_core_99_38.cache.gz.tbi
> -rwxrwxrwx  0 Jun 12 14:55 vagrent.human.GRCh38.homo_sapiens_core_99_38.fa

Connecting via FTP fails due to time , which is why I tried using local files.
I am running it using the cgpwgs Docker image, can it be the an issue? Does it need all the set of references specified [in the cgpwgs docker wiki](https://github.com/cancerit/dockstore-cgpwgs/wiki/Running-under-singularity) for the full pipeline run to create the cache for VAGrENT?

**Comment by AndyMenzies** [comment]
Hi

I hate to say this, but it works for me.  If I get the external reference files

wget ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
wget ftp://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/ncrna/Homo_sapiens.GRCh38.ncrna.fa.gz
wget ftp://ftp.ensembl.org/pub/release-99/gff3/homo_sapiens/Homo_sapiens.GRCh38.99.gff3.gz
wget https://ftp.ncbi.nlm.nih.gov/pub/CCDS/current_human/CCDS2Sequence.current.txt

And then run

Admin_EnsemblReferenceFileGenerator.pl --species Human --assembly GRCh38 --database homo_sapiens_core_99_38 --features Homo_sapiens.GRCh38.99.gff3.gz --cdna_fa Homo_sapiens.GRCh38.cdna.all.fa.gz --ncrna_fa Homo_sapiens.GRCh38.ncrna.fa.gz --trans_list trans.list -fai genome.fa.fai -ccds CCDS2Sequence.current.txt -o out_dir/

Where my genome.fa.fai file is of the format

chr1    248956422       112     80      81
chr2    242193529       252068602       80      81
chr3    198295559       497289663       80      81
chr4    190214555       698064029       80      81
….

And my trans.list looks like this

ENST00000389048
ENST00000343823
ENST00000447712
ENST00000409261

I get a cache file and fasta file with content.  Question I should probably have asked at the start, which version of Vagrent are you using?

Andy

**Comment by nvolkovaGEL** [comment]
Hi Andy,
This sounds like a mystery! 

> I get a cache file and fasta file with content.  Question I should probably have asked at the start, which version of Vagrent are you using?

I tried both with versions 3.6.1 (cloned from this GitHub) and 3.5.0 (latest release). All my files come from the same links or look the same way as yours.

This update somehow disappeared from my previous comment, but I wanted to add that I am able to generate a full cache (without the list of transcripts)! Do you think it is some silent perl library misbehavior on my side?

**Comment by AndyMenzies** [comment]
Possibly.  Can you try running it via the docker container? That should eliminate dependancy shenanigans.

https://quay.io/repository/wtsicgp/vagrent

I used the 3.6.1 container (released in May 6th) to generate my results.

**Comment by nvolkovaGEL** [comment]
Hello Andy,
I have solved the issue! Turned out to be the list of transcripts being saved with the wrong end of line symbol, which prevented the parsing script from finding the relevant transcripts in the database. Would you consider adding an message that the cache builder would output if it does not find a transcript in the reference?
Thanks for your help and sorry for the fuss!
All the best,
Nadezda

**Comment by AndyMenzies** [comment]
No problem, glad you solved it. I've been bitten by that in the past, but not in this context.  I'll add a note to the wiki page.
